remove reference to development bundle
jasvrcek/IcsBundle pull request #8
Opened 2022-08-15 16:32 UTC by tacman

Also, the php is now properly displayed.

2022-11-21 09:40 UTC, Boefjim requested changes
Would love to see this merged after these changes!

2022-11-21 09:40 UTC, Boefjim commented on README.md
> +composer req jsvrcek/ics-bundle
Maybe it's a good idea to mark this as a command?

```suggestion
`composer req jsvrcek/ics-bundle`
```

2022-11-21 09:40 UTC, Boefjim commented on README.md
>      }
Since you are using code blocks, the indentation is no longer necessary

2022-11-21 09:40 UTC, Boefjim commented on README.md
> +```php
This is missing a closing line, also then no longer needs indentation

2022-11-28 17:54 UTC, merged

2022-11-28 17:56 UTC, jasvrcek commented
@Boefjim thanks - I've merged and created a new tag, 1.1.

2022-11-28 21:23 UTC, Boefjim commented
> @Boefjim thanks - I've merged and created a new tag, 1.1.

The changes I've made were not actually part of the PR yet since I couldn't edit it directly, so had to add it as suggested changes instead, but I made another PR for it from my own fork if you still want to get the changes merged: #10 

It's also not really necessary to add a new tag since it's just documentation changes :P